# model
num_joints: 21
num_classes: 12
classifier_name: "poseresnet"
detector_name: "SSDLite"

# data
data_path: "data/diver"
save_path: "result.mov"

classes_dict:
  call: 0
  dislike: 1
  fist: 2
  four: 3
  like: 4
  mute: 5
  ok: 6
  one: 7
  palm: 8
  peace: 9
  peace_inverted: 10
  rock: 11
  stop: 12
  stop_inverted: 13
  three: 14
  three2: 15
  two_up: 16
  two_up_inverted: 17
  no_gesture: 18

img_size_for_detection: 320
img_size_for_classification: 256

# result
display: True
