# dataset
data_path: "data/hagrid_crop/train"
num_joints: 21
num_classes: 19

classes_dict:
  call: 0
  dislike: 1
  fist: 2
  four: 3
  like: 4
  mute: 5
  ok: 6
  one: 7
  palm: 8
  peace: 9
  peace_inverted: 10
  rock: 11
  stop: 12
  stop_inverted: 13
  three: 14
  three2: 15
  two_up: 16
  two_up_inverted: 17
  no_gesture: 18

# data preprocess and augmentation
preprocess:
  crop_FOA: False
  resize_FOA: False
  rotate: False
  horizontal_flip: False
  hsv: False
